export const view_options = [
{opt : ["Manage Profile", "/manage_profile"]},
{opt : ["Manage Users", "/manage_user"]},
{opt : ["Manage Transit", "/manage_transit"]},
{opt : ["Manage Site", "/manage_site"]},
{opt : ["Manage Event", "/manage_event"]},
{opt : ["View Staff", "/manage_staff"]},
{opt : ["View Site Report", "/site_report"]},
{opt : ["View Schedule", "/view_schedule"]},
{opt : ["Explore Event", "/explore_event"]},
{opt : ["Explore Site", "/explore_site"]},
{opt : ["View Visit History", "/visit_history"]},
{opt : ["Take Transit", "/take_transit"]},
{opt : ["View Transit History", "/transit_history"]},
];
