export const view_options = [
{opt : ["Manage Profile", "/manage_profile", ['employee', 'admin', 'manager', 'staff']]},
{opt : ["Manage Users", "/manage_user", ['employee', 'admin']]},
{opt : ["Manage Transit", "/manage_transit", ['employee', 'admin']]},
{opt : ["Manage Site", "/manage_site", ['employee', 'admin']]},
{opt : ["Manage Event", "/manage_event", ['employee', 'manager']]},
{opt : ["View Staff", "/manage_staff", ['employee', 'manager']]},
{opt : ["View Site Report", "/site_report", ['employee', 'manager']]},
{opt : ["View Schedule", "/view_schedule", ['employee', 'staff']]},
{opt : ["Explore Event", "/explore_event", ['employee','visitor']]},
{opt : ["Explore Site", "/explore_site", ['employee', 'visitor']]},
{opt : ["View Visit History", "/visit_history", ['employee', 'visitor']]},
{opt : ["Take Transit", "/take_transit", ['employee', 'visitor', 'user']]},
{opt : ["View Transit History", "/transit_history", ['employee', 'visitor', 'user']]},
];
